name: Keep Render Online

on:
  schedule:
    - cron: '*/20 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Visit website
        run: curl -s https://coderax.onrender.com/ping > /dev/null
